// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCvLrcPp-k1e3deHce_Pmv8ztCSHDxrhM',
    appId: '1:1023288290319:web:220a493b64a016cb1dc77a',
    messagingSenderId: '1023288290319',
    projectId: 'moviedb-5ef41',
    authDomain: 'moviedb-5ef41.firebaseapp.com',
    storageBucket: 'moviedb-5ef41.appspot.com',
    measurementId: 'G-RJRXCQCTL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-jNJRXvxxaYr0CyRYM4ahGvJXtozURCs',
    appId: '1:1023288290319:android:2daa17c0b3451d301dc77a',
    messagingSenderId: '1023288290319',
    projectId: 'moviedb-5ef41',
    storageBucket: 'moviedb-5ef41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAF6v-_lqEM7GgoXGqwI8P16JMS34_E70',
    appId: '1:1023288290319:ios:7eee34516c63cfd91dc77a',
    messagingSenderId: '1023288290319',
    projectId: 'moviedb-5ef41',
    storageBucket: 'moviedb-5ef41.appspot.com',
    iosClientId: '1023288290319-3v3cscbttv4e3ecv09jnr94v6pp23d9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.topRateMovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAF6v-_lqEM7GgoXGqwI8P16JMS34_E70',
    appId: '1:1023288290319:ios:7eee34516c63cfd91dc77a',
    messagingSenderId: '1023288290319',
    projectId: 'moviedb-5ef41',
    storageBucket: 'moviedb-5ef41.appspot.com',
    iosClientId: '1023288290319-3v3cscbttv4e3ecv09jnr94v6pp23d9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.topRateMovie',
  );
}
